### ISSUE TITLE
Collection pages showing incorrect  transcription status

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/projects-usep-app#54]
On several pages, for ex. RISD - inscriptions are showing up as transcribed when there is no transcription. Probably because more recent template has <ab> inside the transcription <div> even if it remains empty. Will be collecting more info on this, but it's relatively important to get them to show up correctly.  Am thinking we need to check the length of any content in the transcription, and if it's 0 then there is no transcription.

**Comment by crotger** [comment]
Fixed by recent indexing changes
