### ISSUE TITLE
Bibliography tweaks

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/projects-usep-app#59]
In order of importance:

1. Journals don't have any results if the article only has an author name beyond the abbreviation, for ex. AJA_Bodel  Some of them work because in the past, people only put in the journal volume and didn't use the author name. (would be a problem if more than 1 article in a volume), those correspond to a volume ID. What should they look like in order to fall under a journal volume? AJA_12_Bodel? 
1. Clicking on the name of a corpus or journal doesn't bring up anything. It should either not be clickable, or it should bring up all inscriptions associated with that corpus or journal.
1. unpublished isn't in the list. (it's \@unpub)

We can talk about them on wed.

**Comment by emylonas** [comment]
1 and 2 above are likely to disappear if  #60  is fixed. 

how to fix 3- perhaps add a new transform for unpub.

**Comment by crotger** [comment]
finished implementing this with [usep-data commit a3964f1](/Brown-University-Library/usep-data/commit/a3964f13542cc435423cee985b7bd439ab42bba2)
