### ISSUE TITLE
Advanced search page

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/projects-usep-app#63]
1. remove Decoration from search for now
1. Remove Names (only appear in facets) - full text will get specifics, the list is otherwise too cumbersome
1. Fake: there will be 3 values- Fake, Possibly Fake, Genuine (default) 
1. Order: genre, object, material, language, writing, condition, special chars, condition, fake
1. Need to think about Special characters, as it mixes two kinds of tag.

**Comment by crotger** [comment]
I've dealt with 1, 2, and 4 in my local fork. 3 will take a little longer because of the way we index "fake" currently.

**Comment by crotger** [comment]
also taken care of by decdce9
