### ISSUE TITLE
Facets on Inscription list page

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/projects-usep-app#67]
Remove Decoration
put fake at the top right after transcription status, but only if there are any.
same order as search page
add names at bottom, as it may get quite long
sort names alphabetically? 

add value  to each facet (except fake) that says how many of the hits on the page are not referenced in the facets.

**Comment by crotger** [comment]
addressed in f6da3632d97ca736a8009a73492812842bb2a4d4 and 0f778398bce0382f1eff401babdc649b7fb9f870
